// Generated by CoffeeScript 1.10.0
(function() {
  $(document).on('selectstart', function() {
    return false;
  }).on('mousewheel', function() {
    return false;
  }).on('dragover', function() {
    return false;
  }).on('dragenter', function() {
    return false;
  }).on('ready', function() {
    var button;
    $('#keyboard-2D')[0].width = $('#canvas').width();
    $('#keyboard-2D')[0].height = $('#canvas').height();
    paper.setup($('#keyboard-2D')[0]);
    console.log(paper.view.width);
    window.gui = new dat.GUI();
    window.loader = new LoaderWidget();
    loader.message('Downloading');
    window.app = new Euphony();
    window.app.lock2DGUI = true;
    button = window.gui.add(window.app, 'saveMidi');
    window.gui.add(window.app, 'lock2DGUI').onChange(function(value) {
      if (!value) {
        player.hide();
        player.autoHide();
      } else {
        player.show();
      }
    });
    window.gui.add({
      speed: 1
    }, 'speed', 0.1, 10).onChange(function(value) {
      app.player.timeWarp = 1.0 / value;
    });
    window.gui.add(app, 'timeDivision', {
      '1/1': 1,
      '1/2': 0.5,
      '1/4': 0.25,
      '1/8': 0.125,
      '1/16': 0.0625,
      '1/32': 0.03125
    }).onChange(app.rain.onTimeDivisionChange);
    window.gui.add(app, 'noteDuration', {
      '1/1': 1,
      '1/2': 0.5,
      '1/4': 0.25,
      '1/8': 0.125,
      '1/16': 0.0625,
      '1/32': 0.03125
    });
    return app.initMidi(function() {
      app.initScene();
      return app.loadBuiltinPlaylist(function(playlist) {
        window.player = new PlayerWidget('#player');
        player.setPlaylist(playlist);
        player.on('pause', app.pause);
        player.on('resume', app.resume);
        player.on('stop', app.stop);
        player.on('play', app.start);
        player.on('progress', app.setProgress);
        player.on('trackchange', function(trackId) {
          return loader.message('Loading MIDI', function() {
            return app.loadBuiltinMidi(trackId, function() {
              return loader.stop(function() {
                return player.play();
              });
            });
          });
        });
        player.on('filedrop', function(midiFile) {
          player.stop();
          return loader.message('Loading MIDI', function() {
            return app.loadMidiFile(midiFile, function() {
              return loader.stop(function() {
                return player.play();
              });
            });
          });
        });
        app.on('progress', player.displayProgress);
        player.show(function() {
          var candidates, id;
          if (window.location.hash) {
            return player.setTrackFromHash();
          } else {
            candidates = [3, 5, 6, 7, 10, 11, 12, 13, 14, 16, 19, 30];
            id = Math.floor(Math.random() * candidates.length);
            return player.setTrack(candidates[id]);
          }
        });
        setTimeout((function() {
          if (!window.app.lock2DGUI) {
            player.hide();
            return player.autoHide();
          }
        }), 5000);
        return $(document).on('drop', function(event) {
          var file, files, reader;
          event || (event = window.event);
          event.preventDefault();
          event.stopPropagation();
          event = event.originalEvent || event;
          files = event.files || event.dataTransfer.files;
          file = files[0];
          reader = new FileReader();
          reader.onload = function(e) {
            var midiFile;
            midiFile = e.target.result;
            player.stop();
            return loader.message('Loading MIDI', function() {
              return app.loadMidiFile(midiFile, function() {
                return loader.stop(function() {
                  return player.play();
                });
              });
            });
          };
          return reader.readAsDataURL(file);
        });
      });
    });
  });

}).call(this);
